Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "forwarded_port", guest: 80, host: 8080 
  config.vm.network "private_network", ip: "172.16.1.101",
    hostonly: true
end